# Generated by Django 3.1.11 on 2021-06-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='symptom',
            field=models.TextField(blank=True, null=True),
        ),
    ]
