# Generated by Django 3.1.11 on 2021-06-15 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usertypes', '0009_auto_20210614_1030'),
        ('appointments', '0002_appointment_symptom'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'date', 'timeslot')},
        ),
    ]
