# Generated by Django 3.1.11 on 2021-06-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertypes', '0002_auto_20210610_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
