# Generated by Django 3.1.11 on 2021-06-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertypes', '0005_auto_20210611_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='if_filled_in',
            field=models.BooleanField(default=False),
        ),
    ]
