# Generated by Django 3.1.11 on 2021-06-11 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usertypes', '0006_patient_if_filled_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='if_filled_in',
            new_name='is_filled_in',
        ),
    ]
