# Generated by Django 3.1.11 on 2021-06-14 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usertypes', '0008_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specialization',
            new_name='specialty',
        ),
    ]
