# Generated by Django 3.1.11 on 2021-06-18 13:59

from django.db import migrations, models
import usertypes.models


class Migration(migrations.Migration):

    dependencies = [
        ('usertypes', '0009_auto_20210614_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=usertypes.models.user_directory_path),
        ),
    ]
