# Generated by Django 3.1.11 on 2021-06-19 09:24

from django.db import migrations, models
import usertypes.models


class Migration(migrations.Migration):

    dependencies = [
        ('usertypes', '0010_doctor_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='picture',
            field=models.ImageField(blank=True, default='doctor-default.jpg', null=True, upload_to=usertypes.models.user_directory_path),
        ),
    ]
